/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UxUiRouteImport } from './routes/ux-ui'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'

const UxUiRoute = UxUiRouteImport.update({
  id: '/ux-ui',
  path: '/ux-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ux-ui': typeof UxUiRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ux-ui': typeof UxUiRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ux-ui': typeof UxUiRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/ux-ui' | '/proyectos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/ux-ui' | '/proyectos/$slug'
  id: '__root__' | '/' | '/sitemap.xml' | '/ux-ui' | '/proyectos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UxUiRoute: typeof UxUiRoute
  ProyectosSlugRoute: typeof ProyectosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ux-ui': {
      id: '/ux-ui'
      path: '/ux-ui'
      fullPath: '/ux-ui'
      preLoaderRoute: typeof UxUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UxUiRoute: UxUiRoute,
  ProyectosSlugRoute: ProyectosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
